stages:
  - build
  # 代码同步
  - sync

# 参考：https://docs.gitlab.cn/jh/ci/docker/using_docker_build.html
build:
  variables:
    # When you use the dind service, you must instruct Docker to talk with
    # the daemon started inside of the service. The daemon is available
    # with a network connection instead of the default
    # /var/run/docker.sock socket. Docker 19.03 does this automatically
    # by setting the DOCKER_HOST in
    # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03/docker-entrypoint.sh#L23-L29
    #
    # The 'docker' hostname is the alias of the service container as described at
    # https://docs.gitlab.com/ee/ci/services/#accessing-the-services.
    #
    # Specify to Docker where to create the certificates. Docker
    # creates them automatically on boot, and creates
    # `/certs/client` to share between the service and job
    # container, thanks to volume mount from config.toml
    DOCKER_TLS_CERTDIR: "/certs"
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo $DOCKER_PORT
    - echo $DOCKER_PORT_2375_TCP
    - echo $DOCKER_PORT_2375_TCP_PROTO
    - echo $DOCKER_PORT_2375_TCP_PORT
    - echo $DOCKER_PORT_2375_TCP_ADDR
    - echo $DOCKER_PORT_2376_TCP
    - echo $DOCKER_PORT_2376_TCP_PROTO
    - echo $DOCKER_PORT_2376_TCP_PORT
    - echo $DOCKER_PORT_2376_TCP_ADDR
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_PIPELINE_ID
    - docker build -t $CI_REGISTRY_IMAGE/my-docker-image:$CI_PIPELINE_ID .
    - docker images
    - docker tag $CI_REGISTRY_IMAGE/my-docker-image:$CI_PIPELINE_ID $CI_REGISTRY_IMAGE/my-docker-image:latest
    - docker images
    - docker push $CI_REGISTRY_IMAGE/my-docker-image:$CI_PIPELINE_ID
    - docker push $CI_REGISTRY_IMAGE/my-docker-image:latest
    # 使用
    # --rm：运行结束后删除
    # docker run --rm $CI_REGISTRY_IMAGE/my-docker-image:$CI_PIPELINE_ID
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  rules:
    - if: $CI_COMMIT_TAG

# 嵌入
include:
  # 同步代码
  - /sync.yml
